apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: craftista
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kenzo213/craftista.git
    targetRevision: main
    path: helm/craftista
    helm:
      releaseName: craftista
  destination:
    server: https://kubernetes.default.svc
    namespace: craftista
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
